# Generated by Django 6.0.2 on 2026-02-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_sent',
            new_name='created_at',
        ),
    ]
