# Generated by Django 6.0.2 on 2026-02-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_sync_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
    ]
