# Generated by Django 6.0.1 on 2026-02-22 17:23

import home.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_size',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF, WebP). Max 5MB, recommended 200x200px or larger.', null=True, upload_to='profile/', validators=[home.validators.validate_profile_image]),
        ),
    ]
